version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "weekly"
